// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package livekit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecordingServiceClient is the client API for RecordingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordingServiceClient interface {
	// Starts a room
	StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*StartRecordingResponse, error)
	// Adds an rtmp output to a live recording
	AddOutput(ctx context.Context, in *AddOutputRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Removes an rtmp output from a live recording
	RemoveOutput(ctx context.Context, in *RemoveOutputRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Ends a recording
	EndRecording(ctx context.Context, in *EndRecordingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type recordingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordingServiceClient(cc grpc.ClientConnInterface) RecordingServiceClient {
	return &recordingServiceClient{cc}
}

func (c *recordingServiceClient) StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*StartRecordingResponse, error) {
	out := new(StartRecordingResponse)
	err := c.cc.Invoke(ctx, "/livekit.RecordingService/StartRecording", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingServiceClient) AddOutput(ctx context.Context, in *AddOutputRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/livekit.RecordingService/AddOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingServiceClient) RemoveOutput(ctx context.Context, in *RemoveOutputRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/livekit.RecordingService/RemoveOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingServiceClient) EndRecording(ctx context.Context, in *EndRecordingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/livekit.RecordingService/EndRecording", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordingServiceServer is the server API for RecordingService service.
// All implementations must embed UnimplementedRecordingServiceServer
// for forward compatibility
type RecordingServiceServer interface {
	// Starts a room
	StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error)
	// Adds an rtmp output to a live recording
	AddOutput(context.Context, *AddOutputRequest) (*emptypb.Empty, error)
	// Removes an rtmp output from a live recording
	RemoveOutput(context.Context, *RemoveOutputRequest) (*emptypb.Empty, error)
	// Ends a recording
	EndRecording(context.Context, *EndRecordingRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRecordingServiceServer()
}

// UnimplementedRecordingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRecordingServiceServer struct {
}

func (UnimplementedRecordingServiceServer) StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRecording not implemented")
}
func (UnimplementedRecordingServiceServer) AddOutput(context.Context, *AddOutputRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOutput not implemented")
}
func (UnimplementedRecordingServiceServer) RemoveOutput(context.Context, *RemoveOutputRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveOutput not implemented")
}
func (UnimplementedRecordingServiceServer) EndRecording(context.Context, *EndRecordingRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndRecording not implemented")
}
func (UnimplementedRecordingServiceServer) mustEmbedUnimplementedRecordingServiceServer() {}

// UnsafeRecordingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordingServiceServer will
// result in compilation errors.
type UnsafeRecordingServiceServer interface {
	mustEmbedUnimplementedRecordingServiceServer()
}

func RegisterRecordingServiceServer(s grpc.ServiceRegistrar, srv RecordingServiceServer) {
	s.RegisterService(&RecordingService_ServiceDesc, srv)
}

func _RecordingService_StartRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingServiceServer).StartRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/livekit.RecordingService/StartRecording",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingServiceServer).StartRecording(ctx, req.(*StartRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingService_AddOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingServiceServer).AddOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/livekit.RecordingService/AddOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingServiceServer).AddOutput(ctx, req.(*AddOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingService_RemoveOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingServiceServer).RemoveOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/livekit.RecordingService/RemoveOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingServiceServer).RemoveOutput(ctx, req.(*RemoveOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingService_EndRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingServiceServer).EndRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/livekit.RecordingService/EndRecording",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingServiceServer).EndRecording(ctx, req.(*EndRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordingService_ServiceDesc is the grpc.ServiceDesc for RecordingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livekit.RecordingService",
	HandlerType: (*RecordingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRecording",
			Handler:    _RecordingService_StartRecording_Handler,
		},
		{
			MethodName: "AddOutput",
			Handler:    _RecordingService_AddOutput_Handler,
		},
		{
			MethodName: "RemoveOutput",
			Handler:    _RecordingService_RemoveOutput_Handler,
		},
		{
			MethodName: "EndRecording",
			Handler:    _RecordingService_EndRecording_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livekit_recording.proto",
}
